name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        working-directory: popo2

      - name: Lint
        run: npm run lint
        working-directory: popo2

      - name: Run tests
        run: npm test
        working-directory: popo2

      - name: Build (electron-builder)
        run: npm run build
        working-directory: popo2

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: popo2-windows-build
          path: popo2/release