name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint (skip if no config)
        shell: pwsh
        run: |
          if (Test-Path ".eslintrc.js" -or Test-Path ".eslintrc.cjs" -or Test-Path ".eslintrc.json" -or Test-Path ".eslint.config.js" -or Test-Path ".eslint.config.cjs" -or Test-Path ".eslint.config.mjs") {
            npm run lint
          } else {
            Write-Host "No ESLint config found, skipping lint."
          }

      - name: Run tests
        run: npm test

      - name: Build (electron-builder)
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: popo2-windows-build
          path: release