name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-release:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        working-directory: popo2

      - name: Build installer (electron-builder)
        run: npm run build
        working-directory: popo2

      - name: Build portable zip (electron-packager)
        run: npm run pack:win
        working-directory: popo2

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            popo2/release/*.zip
            popo2/release/*/*.zip
            popo2/release/*/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}